<?
  /* DATOS DE CONEXIÓN DE LA BASE DE DATOS */
    $GLOBALS['BD_SERVER'] = "*****";
    $GLOBALS['BD_NAME'] = '***';
    $GLOBALS['BD_USER'] = '*******';
    $GLOBALS['BD_PASS'] = '*******';

  /*ESTABLECE SI LA BASE DE DATOS QUE ALMACENA LAS CREDENCIALES DE LOGIN
    Y LAS SESIONES ES UNA BASE DE DATOS DIFERENTE O NO [POR DEFECTO = DIFERENTES]*/
    $GLOBALS['DISABLE_SECURITY_DB'] = false;
    $GLOBALS['SECURITY_DB_SUFIX'] = "_security";

  /* ESTABLECE QUÉ ERRORES DE PHP SON NOTIFICADOS */
    $GLOBALS['ERROR_REPORTING_LEVEL'] = E_ALL;

  /* IDIOMA POR DEFECTO */
    $GLOBALS['LANG'] = 'es';
?>
